name: Feature Branch Workflow

on:
  push:
    branches:
      - "feat/*"
      - "fix/*"
  pull_request:
    branches:
      - "feat/*"
      - "fix/*"

permissions:
  contents: read          # Allows access to repository content
  packages: read          # Allows access to packages
  actions: read           # Allows reusable workflows
  security-events: write  # Allows uploading security results

jobs:

  lint-and-test:
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.12"

  analysis:
    needs: lint-and-test
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true
  
  build:
    needs: Analysis
    uses: ./.github/workflows/build.yml
    with:
      python-version: "3.12"
