name: Feature Branch Workflow

on:
  push:
    branches:
      - "feat/*"
      - "fix/*"
  pull_request:
    branches:
      - "feat/*"
      - "fix/*"

permissions:
  actions: read
  security-events: write

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.10"
  Analysis:
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true
