# Workflow Name: Release Workflow
# Description: This workflow runs for release branches (`releases/*`) to validate changes,
# perform code analysis, build the project, and optionally create a Docker image.
name: Release Workflow

on:
  # Trigger for pull requests targeting release branches
  pull_request:
    branches:
      - releases/*

  # Trigger when a commit is pushed to a release branch (after a PR merge)
  push:
    branches:
      - releases/*

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  # Job 1: Validate Changes
  # Description: Lints the code and runs tests to validate changes in the release branch.
  validate_changes:
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.12"

  # Job 2: Analyze Code
  # Description: Runs advanced code analysis (e.g., CodeQL) after validating changes.
  # Dependency: Waits for `validate_changes` to complete successfully.
  analyze_codeql:
    needs: validate_changes
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true

  # Job 3: Build and Package
  # Description: Builds the project after validation and code analysis, but only for `push` events.
  # Dependency: Waits for both `validate_changes` and `analyze_codeql` to complete successfully.
  build_and_package:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases') }}
    needs: [validate_changes, analyze_codeql]
    uses: ./.github/workflows/build.yml
    with:
      python-version: "3.12"

  # Job 4: Build Docker Image
  # Description: Builds and pushes a pre-release Docker image for release branches after all prior jobs.
  # Dependency: Waits for `validate_changes`, `analyze_codeql`, and `build_and_package` to complete.
  build_docker_image:
    if: ${{ github.event_name == 'push' }}
    needs: [validate_changes, analyze_codeql, build_and_package]
    uses: ./.github/workflows/build_image.yml
    with:
      docker_context: .
      dockerfile: ./Dockerfile
      image_name: pre_release_image
      tags: |
        type=ref,event=branch
        type=raw,value=latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
